In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
trips = pd.read_csv('data/trip.csv')
weather = pd.read_csv('data/weather.csv')
stations = pd.read_csv('data/station.csv')
#status = pd.read_csv('data/status.csv', low_memory= False)

In [3]:
trips.head()

,id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
0,4576,63,8/29/2013 14:13,South Van Ness at Market,66,8/29/2013 14:14,South Van Ness at Market,66,520,Subscriber,94127
1,4607,70,8/29/2013 14:42,San Jose City Hall,10,8/29/2013 14:43,San Jose City Hall,10,661,Subscriber,95138
2,4130,71,8/29/2013 10:16,Mountain View City Hall,27,8/29/2013 10:17,Mountain View City Hall,27,48,Subscriber,97214
3,4251,77,8/29/2013 11:29,San Jose City Hall,10,8/29/2013 11:30,San Jose City Hall,10,26,Subscriber,95060
4,4299,83,8/29/2013 12:02,South Van Ness at Market,66,8/29/2013 12:04,Market at 10th,67,319,Subscriber,94103

In [4]:
trips.describe()

,id,duration,start_station_id,end_station_id,bike_id
count,669959.000000,6.699590e+05,669959.000000,669959.000000,669959.000000
mean,460382.009899,1.107950e+03,57.851876,57.837438,427.587620
std,264584.458487,2.225544e+04,17.112474,17.200142,153.450988
min,4069.000000,6.000000e+01,2.000000,2.000000,9.000000
25%,231082.500000,3.440000e+02,50.000000,50.000000,334.000000
50%,459274.000000,5.170000e+02,62.000000,62.000000,440.000000
75%,692601.000000,7.550000e+02,70.000000,70.000000,546.000000
max,913460.000000,1.727040e+07,84.000000,84.000000,878.000000

In [5]:
trips.duration.describe()

count    6.699590e+05
mean     1.107950e+03
std      2.225544e+04
min      6.000000e+01
25%      3.440000e+02
50%      5.170000e+02
75%      7.550000e+02
max      1.727040e+07
Name: duration, dtype: float64

In [6]:
# Paso duration a minutos.
trips.duration /= 60

In [7]:
trips.duration.describe()

count    669959.000000
mean         18.465831
std         370.923950
min           1.000000
25%           5.733333
50%           8.616667
75%          12.583333
max      287840.000000
Name: duration, dtype: float64

In [8]:
trips[trips.duration > 10000]

,id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
80510,111309,12037.266667,11/30/2013 13:29,University and Emerson,35,12/8/2013 22:06,University and Emerson,35,247,Customer,94301
93400,129504,10322.033333,12/18/2013 9:16,San Jose Diridon Caltrain Station,2,12/25/2013 13:18,SJSU 4th at San Carlos,12,653,Subscriber,94041
195379,361321,11922.316667,7/13/2014 5:50,Arena Green / SAP Center,14,7/21/2014 12:32,Adobe on Almaden,5,251,Customer,nil
223016,323594,11941.333333,6/13/2014 16:57,Harry Bridges Plaza (Ferry Building),50,6/21/2014 23:59,Civic Center BART (7th at Market),72,633,Subscriber,94131
287337,237942,10746.183333,4/6/2014 3:37,South Van Ness at Market,66,4/13/2014 14:44,Clay at Battery,41,369,Customer,94014
371066,841176,18892.333333,7/10/2015 10:35,University and Emerson,35,7/23/2015 13:27,University and Emerson,35,262,Customer,94306
382718,825850,35616.666667,6/28/2015 21:50,Market at Sansome,77,7/23/2015 15:27,Yerba Buena Center of the Arts (3rd @ Howard),68,466,Customer,97213
421839,774999,11481.650000,5/20/2015 15:27,Palo Alto Caltrain Station,34,5/28/2015 14:49,California Ave Caltrain Station,36,230,Customer,nil
440339,750192,30876.500000,5/2/2015 6:17,San Antonio Shopping Center,31,5/23/2015 16:53,Castro Street and El Camino Real,32,680,Subscriber,94024
443792,745640,10187.333333,4/29/2015 9:41,University and Emerson,35,5/6/2015 11:28,San Antonio Shopping Center,31,196,Customer,81
524518,635263,10038.966667,2/8/2015 3:09,San Jose Civic Center,3,2/15/2015 2:28,San Jose Civic Center,3,9,Customer,89451
524521,635260,10932.316667,2/8/2015 3:05,San Jose Civic Center,3,2/15/2015 17:17,SJSU 4th at San Carlos,12,132,Customer,89451
573566,568474,287840.000000,12/6/2014 21:59,South Van Ness at Market,66,6/24/2015 20:18,2nd at Folsom,62,535,Customer,95531
606063,522337,12007.566667,10/30/2014 8:29,Redwood City Caltrain Station,22,11/7/2014 15:36,Stanford in Redwood City,25,692,Customer,94010

In [9]:
trips.start_date = pd.to_datetime(trips.start_date, format='%m/%d/%Y %H:%M')
trips.end_date = pd.to_datetime(trips.end_date, format='%m/%d/%Y %H:%M')

In [10]:
trips.dtypes

id                             int64
duration                     float64
start_date            datetime64[ns]
start_station_name            object
start_station_id               int64
end_date              datetime64[ns]
end_station_name              object
end_station_id                 int64
bike_id                        int64
subscription_type             object
zip_code                      object
dtype: object

In [11]:
diasDistintos = trips[trips.start_date.dt.date != trips.end_date.dt.date]

In [23]:
# Cuánta gente se 'robó' bicicletas
# (Consideramos robada cuando tardó + de 1 semana en devolver)
unaSemana = 60 * 24 * 7
ladrones = diasDistintos[diasDistintos.duration > unaSemana]
ladrones

,id,duration,start_date,start_station_name,start_station_id,end_date,end_station_name,end_station_id,bike_id,subscription_type,zip_code
80510,111309,12037.266667,2013-11-30 13:29:00,University and Emerson,35,2013-12-08 22:06:00,University and Emerson,35,247,Customer,94301
93400,129504,10322.033333,2013-12-18 09:16:00,San Jose Diridon Caltrain Station,2,2013-12-25 13:18:00,SJSU 4th at San Carlos,12,653,Subscriber,94041
195379,361321,11922.316667,2014-07-13 05:50:00,Arena Green / SAP Center,14,2014-07-21 12:32:00,Adobe on Almaden,5,251,Customer,nil
223016,323594,11941.333333,2014-06-13 16:57:00,Harry Bridges Plaza (Ferry Building),50,2014-06-21 23:59:00,Civic Center BART (7th at Market),72,633,Subscriber,94131
287337,237942,10746.183333,2014-04-06 03:37:00,South Van Ness at Market,66,2014-04-13 14:44:00,Clay at Battery,41,369,Customer,94014
371066,841176,18892.333333,2015-07-10 10:35:00,University and Emerson,35,2015-07-23 13:27:00,University and Emerson,35,262,Customer,94306
382718,825850,35616.666667,2015-06-28 21:50:00,Market at Sansome,77,2015-07-23 15:27:00,Yerba Buena Center of the Arts (3rd @ Howard),68,466,Customer,97213
421839,774999,11481.650000,2015-05-20 15:27:00,Palo Alto Caltrain Station,34,2015-05-28 14:49:00,California Ave Caltrain Station,36,230,Customer,nil
440339,750192,30876.500000,2015-05-02 06:17:00,San Antonio Shopping Center,31,2015-05-23 16:53:00,Castro Street and El Camino Real,32,680,Subscriber,94024
443792,745640,10187.333333,2015-04-29 09:41:00,University and Emerson,35,2015-05-06 11:28:00,San Antonio Shopping Center,31,196,Customer,81
524521,635260,10932.316667,2015-02-08 03:05:00,San Jose Civic Center,3,2015-02-15 17:17:00,SJSU 4th at San Carlos,12,132,Customer,89451
573566,568474,287840.000000,2014-12-06 21:59:00,South Van Ness at Market,66,2015-06-24 20:18:00,2nd at Folsom,62,535,Customer,95531
606063,522337,12007.566667,2014-10-30 08:29:00,Redwood City Caltrain Station,22,2014-11-07 15:36:00,Stanford in Redwood City,25,692,Customer,94010